"use client";

import { useState, type CSSProperties } from "react";

import { useDemo } from "@/components/demo-context";
import { Icon } from "@/components/icon";
import { Badge, Button, Card, PageHeader } from "@/components/ui";

export function WebsiteView() {
  const { state, patchSettings, patchVehicle, formatMoney } = useDemo();
  const [device, setDevice] = useState<"desktop" | "mobile">("desktop");
  const featured = state.vehicles.filter((vehicle) => vehicle.featured && vehicle.status !== "Sold").slice(0, 3);

  return (
    <>
      <PageHeader
        eyebrow="Website management"
        title="Dealership website"
        description="Control the content that customers see without touching the website code."
        actions={
          <>
            <Button icon="eye">Preview website</Button>
            <Button icon="external" variant="primary">Publish changes</Button>
          </>
        }
      />

      <section className="website-status-row">
        <Card className="site-status-card"><span className="status-orb online"><i /></span><div><strong>Website online</strong><small>All systems operational</small></div><Badge tone="green">Live</Badge></Card>
        <Card className="site-status-card"><span className="summary-icon summary-icon-blue"><Icon name="eye" width={18} height={18} /></span><div><strong>3,842 visitors</strong><small>Last 30 days</small></div><span className="success-text">+12.4%</span></Card>
        <Card className="site-status-card"><span className="summary-icon summary-icon-purple"><Icon name="users" width={18} height={18} /></span><div><strong>24 enquiries</strong><small>Generated by website</small></div><span className="success-text">+9.8%</span></Card>
      </section>

      <section className="website-layout">
        <div className="website-controls">
          <Card className="panel settings-card">
            <div className="panel-header"><div><p className="panel-kicker">Brand</p><h2>Website identity</h2></div><Badge tone="neutral">Shared demo</Badge></div>
            <div className="brand-preview-row">
              <div className="brand-placeholder"><Icon name="car" width={25} height={25} /><span>DEALER<span>DESK</span></span></div>
              <Button icon="edit">Change logo</Button>
            </div>
            <label className="form-field"><span>Dealership name</span><input className="form-control" value={state.settings.name} onChange={(event) => patchSettings({ name: event.target.value })} /></label>
            <label className="form-field"><span>Accent colour</span><span className="color-control"><input type="color" value={state.settings.accent} onChange={(event) => patchSettings({ accent: event.target.value })} /><input className="form-control" value={state.settings.accent} onChange={(event) => patchSettings({ accent: event.target.value })} /></span></label>
          </Card>

          <Card className="panel settings-card">
            <div className="panel-header"><div><p className="panel-kicker">Homepage</p><h2>Visible sections</h2></div></div>
            <div className="section-control-list">
              <label className="switch-row"><span><strong>Featured vehicles</strong><small>Highlight selected inventory on the homepage.</small></span><input type="checkbox" defaultChecked /><i /></label>
              <label className="switch-row"><span><strong>Finance promotion</strong><small>Show financing and monthly payment messaging.</small></span><input type="checkbox" checked={state.settings.showFinancing} onChange={(event) => patchSettings({ showFinancing: event.target.checked })} /><i /></label>
              <label className="switch-row"><span><strong>Trade-in callout</strong><small>Invite customers to value their existing vehicle.</small></span><input type="checkbox" checked={state.settings.showTradeIn} onChange={(event) => patchSettings({ showTradeIn: event.target.checked })} /><i /></label>
              <label className="switch-row"><span><strong>Customer reviews</strong><small>Display verified dealership testimonials.</small></span><input type="checkbox" defaultChecked /><i /></label>
            </div>
          </Card>

          <Card className="panel settings-card">
            <div className="panel-header"><div><p className="panel-kicker">Inventory</p><h2>Featured vehicles</h2></div><span className="panel-count">{featured.length}/3 selected</span></div>
            <div className="featured-control-list">
              {state.vehicles.filter((vehicle) => vehicle.status !== "Sold").slice(0, 6).map((vehicle) => (
                <label className="featured-control-row" key={vehicle.id}>
                  <span className="vehicle-table-thumb"><Icon name="car" width={22} height={22} /></span>
                  <span><strong>{vehicle.make} {vehicle.model}</strong><small>{vehicle.year} · {formatMoney(vehicle.price)}</small></span>
                  <input type="checkbox" checked={vehicle.featured} onChange={(event) => patchVehicle(vehicle.id, { featured: event.target.checked })} />
                </label>
              ))}
            </div>
          </Card>
        </div>

        <div className="website-preview-column">
          <div className="preview-toolbar">
            <div><span className="preview-dot red" /><span className="preview-dot amber" /><span className="preview-dot green" /></div>
            <span className="preview-url"><Icon name="monitor" width={14} height={14} />yourdealership.com</span>
            <div className="device-switch"><button className={device === "desktop" ? "active" : ""} type="button" onClick={() => setDevice("desktop")}><Icon name="monitor" width={16} height={16} /></button><button className={device === "mobile" ? "active" : ""} type="button" onClick={() => setDevice("mobile")}><Icon name="phone" width={16} height={16} /></button></div>
          </div>
          <div className={`site-preview-frame ${device}`}>
            <div className="mock-site" style={{ "--mock-accent": state.settings.accent } as CSSProperties}>
              <header className="mock-site-header"><span className="mock-logo"><Icon name="car" width={18} height={18} />DEALERDESK</span><nav><span>Vehicles</span><span>Sell your car</span><span>Finance</span><span>About</span></nav><button>Contact us</button></header>
              <section className="mock-hero"><div><span>PREMIUM VEHICLES, PERSONALLY SELECTED</span><h2>Find a car you will love to drive.</h2><p>Explore inspected vehicles with transparent history and personal support from enquiry to handover.</p><button>Browse vehicles <Icon name="chevronRight" width={13} height={13} /></button></div><div className="mock-hero-car"><Icon name="car" width={108} height={108} /></div></section>
              <section className="mock-stock"><div className="mock-section-title"><div><span>AVAILABLE NOW</span><h3>Featured vehicles</h3></div><button>View all</button></div><div className="mock-vehicle-grid">{featured.map((vehicle) => <article key={vehicle.id}><div><Icon name="car" width={48} height={48} /></div><span>{vehicle.year}</span><h4>{vehicle.make} {vehicle.model}</h4><p>{vehicle.variant}</p><strong>{formatMoney(vehicle.price)}</strong></article>)}</div></section>
              {state.settings.showFinancing ? <section className="mock-finance"><div><span>FLEXIBLE FINANCE</span><h3>Drive sooner with a plan that fits.</h3><p>Clear options, fast decisions and support throughout your purchase.</p></div><button>Calculate payment</button></section> : null}
              <footer className="mock-footer"><strong>{state.settings.name}</strong><span>{state.settings.phone} · {state.settings.email}</span></footer>
            </div>
          </div>
          <p className="preview-disclaimer"><Icon name="sparkles" width={15} height={15} />Live preview reflects changes in this demo. Publishing is disabled for visitors.</p>
        </div>
      </section>
    </>
  );
}
